version: "3.2"
services:
  deploy_dataflow_template:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    environment:
      - GCP_REGION
      - GCP_PROJECT
      - APP_QUERY
      - APP_SERVER
      - APP_TOPIC
      - BIGQUERY_TEMPLATE_LOCATION
      - AUTOSCALING_ALGORITHM
      - STAGING_LOCATION
      - TEMPLATE_LOCATION
      - SUBNETWORK
      - NETWORK
    volumes:
      - ${PWD}:/app
      - ${HOME}/.google-credentials:/.google-credentials
      #- ${HOME}/scentregroup/workflows-deployer-dkimg/workflows-test.json:/.google-credentials
